language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_SDKS=android-23

android:
  components:
    - tools
    - build-tools-23.0.1
    - android-23

script: gradle build
